[Partitions]

# erase
protect1_erase=0
protect2_erase=0
expdb_erase=0
para_erase=0
kb_erase=0
dkb_erase=0
metadata_erase=0
nvram_erase=0
# flash
pgpt=0
nvram=0
nvcfg=0
nvdata=0
persist=0
preloader=0
boot_para=0
cam_vpu1=0
cam_vpu2=0
cam_vpu3=0
lk=0
lk2=0
boot=0
recovery=0
logo=0
dtbo=0
frp=0
tee1=0
tee2=0
vbmeta=0
system=0
vendor=0
factory=0
cache=0
