name: Build CVE-2021-1961 Exploit

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cross compiler
        run: sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu

      - name: Compile exploit
        run: |
          aarch64-linux-gnu-gcc -static -o exploit exploit.c -lpthread
          strip exploit

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cve-2021-1961
          path: exploit
