name: Build 
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nanasess/setup-ndk@v1
        with:
          ndk-version: 'r25c'

      - name: Compile PoC
        run: |
          $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android28-clang++ \
            -o poc poc.cpp -lbinder -lutils

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: poc
          path: poc
